<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19171" started-at="2018-03-12T16:41:17Z" finished-at="2018-03-12T16:41:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19171" started-at="2018-03-12T16:41:17Z" finished-at="2018-03-12T16:41:36Z">
      <class name="org.automaion.testcases.TC_001_ValidateLoginFunctionality">
        <test-method status="PASS" signature="intiateDriverInstance()[pri:0, instance:org.automaion.testcases.TC_001_ValidateLoginFunctionality@754ba872]" name="intiateDriverInstance" is-config="true" duration-ms="16134" started-at="2018-03-12T16:41:17Z" finished-at="2018-03-12T16:41:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intiateDriverInstance -->
        <test-method status="FAIL" signature="tc_001_login_fuctionality()[pri:0, instance:org.automaion.testcases.TC_001_ValidateLoginFunctionality@754ba872]" name="tc_001_login_fuctionality" duration-ms="1189" started-at="2018-03-12T16:41:33Z" finished-at="2018-03-12T16:41:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [test123] but found [test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [test123] but found [test]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.automation.pages.LoginPage.enterPassword(LoginPage.java:28)
at org.automaion.testcases.TC_001_ValidateLoginFunctionality.tc_001_login_fuctionality(TC_001_ValidateLoginFunctionality.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_001_login_fuctionality -->
        <test-method status="PASS" signature="failTestScreenshot(org.testng.ITestResult)[pri:0, instance:org.automaion.testcases.TC_001_ValidateLoginFunctionality@754ba872]" name="failTestScreenshot" is-config="true" duration-ms="392" started-at="2018-03-12T16:41:34Z" finished-at="2018-03-12T16:41:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=tc_001_login_fuctionality status=FAILURE method=TC_001_ValidateLoginFunctionality.tc_001_login_fuctionality()[pri:0, instance:org.automaion.testcases.TC_001_ValidateLoginFunctionality@754ba872] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failTestScreenshot -->
        <test-method status="PASS" signature="closeDriverInstace()[pri:0, instance:org.automaion.testcases.TC_001_ValidateLoginFunctionality@754ba872]" name="closeDriverInstace" is-config="true" duration-ms="1355" started-at="2018-03-12T16:41:35Z" finished-at="2018-03-12T16:41:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriverInstace -->
      </class> <!-- org.automaion.testcases.TC_001_ValidateLoginFunctionality -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
